version: '3'
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: cc:latest
    networks:
     - appnet
    volumes:
     - .:/var/www/html
    ports:
     - ${DOCKER_APP_PORT}:80
    working_dir: /var/www/html
  cache:
    image: redis:alpine
    networks:
     - appnet
    volumes:
     - cachedata:/data
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
     - ${DOCKER_DB_PORT}:3306
    networks:
     - appnet
    volumes:
     - dbdata:/var/lib/mysql
  adminer:
    image: adminer:latest
    restart: always
    environment:
      ADMINER_DESIGN: 'hever'
    ports:
      - 9090:8080
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
volumes:
  dbdata:
    driver: local
  cachedata:
    driver: local